apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
