apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2023-03-23T14:09:20Z"
    name: default
    namespace: default
    resourceVersion: "327"
    uid: ccfa6495-d132-41bf-91c6-80ef379365e7
kind: List
metadata:
  resourceVersion: ""
