apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      k8s-app: calico-kube-controllers
    name: calico-kube-controllers
    namespace: calico-system
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        k8s-app: calico-kube-controllers
  status:
kind: List
metadata:
  resourceVersion: ""
